//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taxiSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int Id { get; set; }
        public Nullable<double> Range { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> StartX { get; set; }
        public Nullable<int> StartY { get; set; }
        public Nullable<int> EndX { get; set; }
        public Nullable<int> EndY { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int CarNr { get; set; }
        public int PassengerNr { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
